CREATE TABLE product (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    montant FLOAT
);

INSERT INTO product (name, montant, description) VALUES
('Chocolat', 5.50, 'Un délice riche et sucré pour les amateurs de chocolat.'),
('Coca Cola', 1.20, 'Boisson gazeuse rafraîchissante appréciée dans le monde entier.'),
('Pepsi', 1.10, 'Concurrent direct de Coca, avec un goût distinctif.'),
('Kit Kat', 0.99, 'Barre chocolatée avec des gaufrettes croustillantes.'),
('Snickers', 1.15, 'Barre nourrissante avec du caramel, des cacahuètes et du nougat.'),
('M&M''s', 1.30, 'Bonbons au chocolat colorés avec une coquille de sucre.'),
('Twix', 1.25, 'Biscuit enrobé de caramel et de chocolat.'),
('Hershey''s', 1.40, 'Chocolat au lait classique et doux.'),
('Skittles', 1.10, 'Petits bonbons fruités avec une coquille dure.'),
('Milky Way', 1.30, 'Barre de chocolat au lait moelleuse avec du caramel.'),
('Reese''s', 1.50, 'Coupes de beurre de cacahuète enrobées de chocolat.'),
('Cadbury', 1.70, 'Chocolat au lait réputé pour sa douceur.'),
('Dr Pepper', 1.20, 'Soda unique avec un mélange secret de 23 saveurs.'),
('Sprite', 1.10, 'Soda citron-lime clair et rafraîchissant.'),
('Mountain Dew', 1.30, 'Soda caféiné avec un coup de pouce énergétique.'),
('Nestlé', 1.60, 'Divers produits chocolatés et alimentaires de marque renommée.'),
('Lindt', 2.50, 'Chocolat suisse de luxe connu pour sa finesse.'),
('Haribo', 1.80, 'Gommes fruitées populaires, notamment les ours gommeux.'),
('Starburst', 1.05, 'Bonbons fruités juteux en morceaux.'),
('Barre Mars', 1.20, 'Combinaison de chocolat, caramel et nougat.'),
('Café', 10.00, 'Boisson énergisante et réconfortante, appréciée mondialement.'),
('Thé', 8.50, 'Infusion traditionnelle offrant diverses saveurs et bienfaits.'),
('Biscuits', 2.30, 'Douceurs croustillantes et savoureuses pour toute occasion.'),
('Chips', 2.00, 'Snack salé croustillant, idéal pour les réunions conviviales.'),
('Fromage', 5.00, 'Variété de fromages riches et crémeux pour tous les goûts.'),
('Lait', 0.90, 'Essentiel quotidien, riche en nutriments et en vitamines.'),
('Beurre', 3.25, 'Ingrédient de base pour la cuisine et la pâtisserie.'),
('Pain', 1.45, 'Aliment de base, frais et nourrissant, disponible en plusieurs variétés.'),
('Oeufs', 2.10, 'Source de protéines polyvalente pour de nombreuses recettes.'),
('Tomate', 0.99, 'Fruit juteux souvent utilisé comme un légume dans les cuisines.'),
('Céréales', 3.50, 'Petit-déjeuner nutritif disponible en de nombreuses saveurs.'),
('Oreo', 2.20, 'Biscuits au chocolat avec un fourrage crémeux.'),
('Jus', 2.80, 'Boissons extraites de fruits frais, riches en vitamines.'),
('Eau', 0.50, 'La nécessité quotidienne pour rester hydraté.'),
('Bière', 1.99, 'Boisson alcoolisée traditionnelle à base de houblon.'),
('Vin', 12.00, 'Boisson alcoolisée élégante, issue de la fermentation du raisin.'),
('Whisky', 25.00, 'Spiriteux distillé riche et complexe, vieilli en fûts.'),
('Rhum', 18.00, 'Alcool distillé à partir de la canne à sucre, souvent épicé ou sucré.'),
('Vodka', 15.00, 'Spiriteux clair et puissant, populaire dans les cocktails.'),
('Gin', 17.00, 'Spiriteux aromatisé aux baies de genièvre, base de nombreux cocktails.'),
('Tonic', 0.85, 'Boisson gazeuse souvent utilisée comme mixer pour des cocktails.'),
('Boisson énergétique', 2.00, 'Boisson stimulante pour les moments de besoin énergétique.'),
('Glace', 3.00, 'Dessert congelé, aimé pour sa douceur et sa fraîcheur.'),
('Yaourt', 1.20, 'Produit laitier fermenté, connu pour ses bienfaits pour la santé.'),
('Fruit', 2.50, 'Source naturelle de vitamines et de fibres.'),
('Légumes', 1.50, 'Essentiels pour une alimentation équilibrée, disponibles en diverses variétés.'),
('Poulet', 5.00, 'Viande blanche polyvalente, populaire dans les régimes.'),
('Boeuf', 8.00, 'Viande rouge riche, souvent utilisée pour les steaks et les ragoûts.'),
('Poisson', 10.00, 'Source importante d''oméga-3 et de protéines.'),
('Porc', 6.00, 'Viande savoureuse, utilisée dans divers plats traditionnels.');

