version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: Edge
    ports:
      - "3424:5432"
    volumes:
      - PostgreClassico:/var/lib/postgresql/data

volumes:
  PostgreClassico:
